=== VijayEluri/iucn-sis/org.iucn.sis.server.crazy/src/org/iucn/sis/server/xmlAssessments/assessmentStructure.xsd
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="fieldStructures.xsd" />

	<xs:element name="assessment" type="Assessment" />

	<xs:complexType name="Assessment">
		<xs:sequence>
			<xs:element name="basicInformation" type="AssessmentInformation" maxOccurs="1" />
			<xs:element name="field" type="Field"  maxOccurs="170" minOccurs="0" />
			<xs:element name="tree" type="Tree" maxOccurs="170" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" />
	</xs:complexType>
	
	<xs:complexType name="AssessmentInformation">
		<xs:sequence>
			<xs:element name="speciesName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="commonName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="taxonomicAuthority" type="xs:string" />
			<xs:element name="assessmentType" type="AssessmentType" minOccurs="1" maxOccurs="1" />
			<xs:element name="region" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="kingdom" type="xs:string" minOccurs="1" maxOccurs="1" />						
			<xs:element name="phylum" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="class" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="order" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="family" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="rank" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="infrarank" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="subpopulation" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="plantType" type="xs:boolean" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType> 
	
	<xs:complexType name="AssessmentType">
		<xs:choice>
			<xs:element name="global" />
			<xs:element name="regional" type="xs:string" nillable="false" />
		</xs:choice>	
	</xs:complexType>
	
	<xs:complexType name="References">
		<xs:sequence>
			<xs:element name="referenceId" type="xs:string" nillable="false" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Field">
		<xs:sequence>
			<xs:element name="canonicalName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="classOfService" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="location" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="references" type="References" minOccurs="0" maxOccurs="1" />
			<xs:element name="structures" type="FieldStructure" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="style" type="xs:string" use="optional" />
		<xs:attribute name="id" type="xs:integer" />
	</xs:complexType>
	
	<xs:complexType name="Tree">
		<xs:sequence>
			<xs:element name="canonicalName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="classOfService" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="location" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="references" type="References" minOccurs="0" maxOccurs="1" />
			<xs:element name="treeRoot" type="TreeRoot" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="style" type="xs:string" use="optional" />
		<xs:attribute name="id" type="xs:integer" />
	</xs:complexType>
	
</xs:schema>

=== VijayEluri/iucn-sis/org.iucn.sis.server.crazy/war/WEB-INF/classes/org/iucn/sis/server/xmlAssessments/wombatAssessment3.xml
<assessment id="w0mb4t3"
		xsi:noNamespaceSchemaLocation = "assessmentStructure.xsd"
		xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance">

	<basicInformation>
		<speciesName>womm wombat3</speciesName>
		<commonName>Wombat3!</commonName>
		<taxonomicAuthority>Me</taxonomicAuthority>
		<assessmentType>
			<global />
		</assessmentType>
		<kingdom>wombatius</kingdom>
		<phylum>happiness</phylum>
		<class>funloving</class>
		<order>cool</order>
		<family>small</family>
		<genus>womm</genus>
		<species>wombat3</species>
	</basicInformation>


</assessment>

=== VijayEluri/iucn-sis/org.iucn.sis.server.crazy/src/org/iucn/sis/server/xmlAssessments/wombatAssessment2.xml
<assessment id="w0mb4t2"
		xsi:noNamespaceSchemaLocation = "assessmentStructure.xsd"
		xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance">

	<basicInformation>
		<speciesName>wooo wombat2</speciesName>
		<commonName>Wombat2!</commonName>
		<taxonomicAuthority>You</taxonomicAuthority>
		<assessmentType>
			<global />
		</assessmentType>
		<kingdom>wombatius</kingdom>
		<phylum>sadness</phylum>
		<class>funhating</class>
		<order>hot</order>
		<family>big</family>
		<genus>wooo</genus>
		<species>wombat2</species>
	</basicInformation>

	<field id="0">
			<canonicalName>RangeDocumentation</canonicalName>
			<description>Geographic Range Information</description>
			<classOfService>Documentation</classOfService>
			<location>Distribution</location>
			<references>
				<referenceId>1</referenceId>
				<referenceId>2</referenceId>
			</references>
			<structures>
				<structure>
					<narrative>I live in the woods</narrative>
				</structure>
			</structures>
	</field>
</assessment>

=== VijayEluri/iucn-sis/org.iucn.sis.server.crazy/src/org/iucn/sis/server/xmlAssessments/wombatAssessment5-2.xml
<assessment id="w0mb4t5.2"
		xsi:noNamespaceSchemaLocation = "assessmentStructure.xsd"
		xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance">

	<basicInformation>
		<speciesName>wommy wombat5</speciesName>
		<commonName>Wombat3!</commonName>
		<taxonomicAuthority>Us</taxonomicAuthority>
		<assessmentType>
			<global />
		</assessmentType>
		<kingdom>wombatius</kingdom>
		<phylum>sadness</phylum>
		<class>funhating</class>
		<order>hot</order>
		<family>biggest</family>
		<genus>wommy</genus>
		<species>wombat5</species>
	</basicInformation>

	<field id="0">
			<canonicalName>RangeDocumentation</canonicalName>
			<description>Geographic Range Information</description>
			<classOfService>Documentation</classOfService>
			<location>Distribution</location>
			<references>
				<referenceId>1</referenceId>
				<referenceId>2</referenceId>
			</references>
			<structures>
				<structure>
					<narrative>I live in the ocean</narrative>
				</structure>
			</structures>
	</field>
</assessment>
